// Shared configuration for Kurate
export const RSS_FEEDS = [
    // Sports
    { name: 'ESPN', url: 'https://www.espn.com/espn/rss/news', category: 'sports' },
    { name: 'BBC Sport', url: 'https://feeds.bbci.co.uk/sport/rss.xml', category: 'sports' },
    { name: 'Sky Sports', url: 'https://www.skysports.com/rss/12040', category: 'sports' },

    // Entertainment
    { name: 'Variety', url: 'https://variety.com/feed/', category: 'entertainment' },
    { name: 'The Hollywood Reporter', url: 'https://www.hollywoodreporter.com/feed/', category: 'entertainment' },
    { name: 'Deadline', url: 'https://deadline.com/feed/', category: 'entertainment' },

    // Business
    { name: 'Harvard Business Review', url: 'https://hbr.org/feed', category: 'business' },
    { name: 'Entrepreneur', url: 'https://www.entrepreneur.com/latest.rss', category: 'business' },
    { name: 'Fortune', url: 'https://fortune.com/feed/', category: 'business' },

    // Technology
    { name: 'The Verge', url: 'https://www.theverge.com/rss/index.xml', category: 'technology' },
    { name: 'TechCrunch', url: 'https://techcrunch.com/feed/', category: 'technology' },
    { name: 'Hacker News', url: 'https://hnrss.org/frontpage', category: 'technology' },
    { name: 'Engadget', url: 'https://www.engadget.com/rss.xml', category: 'technology' },
    { name: 'Scour', url: 'https://scour.ing/nrame/rss.xml', category: 'technology' },
    { name: 'simonwillison.net', url: 'https://simonwillison.net/atom/everything/', category: 'technology' },
    { name: 'jeffgeerling.com', url: 'https://www.jeffgeerling.com/blog.xml', category: 'technology' },
    { name: 'seangoedecke.com', url: 'https://www.seangoedecke.com/rss.xml', category: 'technology' },
    { name: 'krebsonsecurity.com', url: 'https://krebsonsecurity.com/feed/', category: 'technology' },
    { name: 'daringfireball.net', url: 'https://daringfireball.net/feeds/main', category: 'technology' },
    { name: 'ericmigi.com', url: 'https://ericmigi.com/rss.xml', category: 'technology' },
    { name: 'antirez.com', url: 'http://antirez.com/rss', category: 'technology' },
    { name: 'idiallo.com', url: 'https://idiallo.com/feed.rss', category: 'technology' },
    { name: 'maurycyz.com', url: 'https://maurycyz.com/index.xml', category: 'technology' },
    { name: 'pluralistic.net', url: 'https://pluralistic.net/feed/', category: 'technology' },
    { name: 'shkspr.mobi', url: 'https://shkspr.mobi/blog/feed/', category: 'technology' },
    { name: 'lcamtuf.substack.com', url: 'https://lcamtuf.substack.com/feed', category: 'technology' },
    { name: 'mitchellh.com', url: 'https://mitchellh.com/feed.xml', category: 'technology' },
    { name: 'dynomight.net', url: 'https://dynomight.net/feed.xml', category: 'technology' },
    { name: 'utcc.utoronto.ca/~cks', url: 'https://utcc.utoronto.ca/~cks/space/blog/?atom', category: 'technology' },
    { name: 'xeiaso.net', url: 'https://xeiaso.net/blog.rss', category: 'technology' },
    { name: 'devblogs.microsoft.com/oldnewthing', url: 'https://devblogs.microsoft.com/oldnewthing/feed', category: 'technology' },
    { name: 'righto.com', url: 'https://www.righto.com/feeds/posts/default', category: 'technology' },
    { name: 'lucumr.pocoo.org', url: 'https://lucumr.pocoo.org/feed.atom', category: 'technology' },
    { name: 'skyfall.dev', url: 'https://skyfall.dev/rss.xml', category: 'technology' },
    { name: 'garymarcus.substack.com', url: 'https://garymarcus.substack.com/feed', category: 'technology' },
    { name: 'rachelbythebay.com', url: 'https://rachelbythebay.com/w/atom.xml', category: 'technology' },
    { name: 'overreacted.io', url: 'https://overreacted.io/rss.xml', category: 'technology' },
    { name: 'timsh.org', url: 'https://timsh.org/rss/', category: 'technology' },
    { name: 'johndcook.com', url: 'https://www.johndcook.com/blog/feed/', category: 'technology' },
    { name: 'gilesthomas.com', url: 'https://gilesthomas.com/feed/rss.xml', category: 'technology' },
    { name: 'matklad.github.io', url: 'https://matklad.github.io/feed.xml', category: 'technology' },
    { name: 'derekthompson.org', url: 'https://www.theatlantic.com/feed/author/derek-thompson/', category: 'technology' },
    { name: 'evanhahn.com', url: 'https://evanhahn.com/feed.xml', category: 'technology' },
    { name: 'terriblesoftware.org', url: 'https://terriblesoftware.org/feed/', category: 'technology' },
    { name: 'rakhim.exotext.com', url: 'https://rakhim.exotext.com/rss.xml', category: 'technology' },
    { name: 'joanwestenberg.com', url: 'https://joanwestenberg.com/rss', category: 'technology' },
    { name: 'xania.org', url: 'https://xania.org/feed', category: 'technology' },
    { name: 'micahflee.com', url: 'https://micahflee.com/feed/', category: 'technology' },
    { name: 'nesbitt.io', url: 'https://nesbitt.io/feed.xml', category: 'technology' },
    { name: 'construction-physics.com', url: 'https://www.construction-physics.com/feed', category: 'technology' },
    { name: 'tedium.co', url: 'https://feed.tedium.co/', category: 'technology' },
    { name: 'susam.net', url: 'https://susam.net/feed.xml', category: 'technology' },
    { name: 'entropicthoughts.com', url: 'https://entropicthoughts.com/feed.xml', category: 'technology' },
    { name: 'buttondown.com/hillelwayne', url: 'https://buttondown.com/hillelwayne/rss', category: 'technology' },
    { name: 'dwarkesh.com', url: 'https://www.dwarkeshpatel.com/feed', category: 'technology' },
    { name: 'borretti.me', url: 'https://borretti.me/feed.xml', category: 'technology' },
    { name: 'wheresyoured.at', url: 'https://www.wheresyoured.at/rss/', category: 'technology' },
    { name: 'jayd.ml', url: 'https://jayd.ml/feed.xml', category: 'technology' },
    { name: 'minimaxir.com', url: 'https://minimaxir.com/index.xml', category: 'technology' },
    { name: 'geohot.github.io', url: 'https://geohot.github.io/blog/feed.xml', category: 'technology' },
    { name: 'paulgraham.com', url: 'http://www.aaronsw.com/2002/feeds/pgessays.rss', category: 'technology' },
    { name: 'filfre.net', url: 'https://www.filfre.net/feed/', category: 'technology' },
    { name: 'blog.pixelmelt.dev', url: 'https://blog.pixelmelt.dev/rss/', category: 'technology' },
    { name: 'martinalderson.com', url: 'https://martinalderson.com/feed.xml', category: 'technology' },
    { name: 'danielchasehooper.com', url: 'https://danielchasehooper.com/feed.xml', category: 'technology' },
    { name: 'chiark.greenend.org.uk/~sgtatham', url: 'https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml', category: 'technology' },
    { name: 'grantslatton.com', url: 'https://grantslatton.com/rss.xml', category: 'technology' },
    { name: 'experimental-history.com', url: 'https://www.experimental-history.com/feed', category: 'technology' },
    { name: 'anildash.com', url: 'https://anildash.com/feed.xml', category: 'technology' },
    { name: 'aresluna.org', url: 'https://aresluna.org/main.rss', category: 'technology' },
    { name: 'michael.stapelberg.ch', url: 'https://michael.stapelberg.ch/feed.xml', category: 'technology' },
    { name: 'miguelgrinberg.com', url: 'https://blog.miguelgrinberg.com/feed', category: 'technology' },
    { name: 'keygen.sh', url: 'https://keygen.sh/blog/feed.xml', category: 'technology' },
    { name: 'mjg59.dreamwidth.org', url: 'https://mjg59.dreamwidth.org/data/rss', category: 'technology' },
    { name: 'computer.rip', url: 'https://computer.rip/rss.xml', category: 'technology' },
    { name: 'tedunangst.com', url: 'https://www.tedunangst.com/flak/rss', category: 'technology' },


    // Other
    { name: 'Lifehacker', url: 'https://lifehacker.com/rss', category: 'other' },
    { name: 'Smithsonian', url: 'https://www.smithsonianmag.com/rss/latest_articles/', category: 'other' },
    { name: 'NPR News', url: 'https://feeds.npr.org/1001/rss.xml', category: 'other' }
];
